// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/rotemtam/ent-grpc-example/ent/runtime.go

const (
	Version = "v0.11.6"                                         // Version of ent codegen.
	Sum     = "h1:fMQwhuzbPv12AXdrAGyHoOcgh9r0D9F8WEsCRoUWxVc=" // Sum of ent codegen.
)
